[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "nyt-connections"
description = "A command-line client for the NYT Connections game"
long-description = "file: README.md"
long-description-content-type = "text/markdown"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Go",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["version"]

[tool.setuptools.commands]
build = "setup.BuildGoBinary"
install = "setup.PostInstallCommand"

[tool.setuptools_scm]

